sudo: required
services:
  - docker

before_install:
  - docker build -t maheshs -f Dockerfile.txt .
languages: node_js
deploy:
  provider: azure_web_apps
  username: sutari.mahesh1@live.com
  password: mother@123
  site: https://docker-mahi.azurewebsites.net