sudo: required
services:
  - docker

before_install:
  - docker build -t maheshs -f Dockerfile.txt .
languages: node_js
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  on:
    branch: release